import { Link } from "react-router";
import type { ClientPurchase } from "../lib/client-workspace.server";

export function ClientBalance({ purchases, hasProfile, canStartProjects }: { purchases: ClientPurchase[]; hasProfile: boolean; canStartProjects: boolean }) {
  const active = purchases.filter(p => p.active && p.granted > 0);
  const monthly = active.filter(p => p.type === "monthly");
  const hours = monthly.reduce((sum, p) => sum + p.remaining, 0) / 60;
  const videos = active.filter(p => p.type === "single").reduce((sum, p) => sum + p.remaining, 0);
  const setupNeeded = purchases.length > 0 && !hasProfile;
  return <div className="mb-7 space-y-5">
    <div className="grid gap-4 sm:grid-cols-2">
      <section className="neo-workspace__panel min-w-0 rounded-3xl p-6" aria-labelledby="subscription-title"><div className="flex items-start justify-between gap-3"><div><p className="neo-workspace__eyebrow">Your subscription</p><h3 id="subscription-title" className="mt-3 text-xl font-bold">{monthly.length ? monthly.map(p => p.name).join(" + ") : "No active monthly plan"}</h3></div><span className="neo-icon-badge inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl"><span className="material-symbols-outlined" aria-hidden="true">calendar_month</span></span></div><p className="mt-3 text-sm leading-6 text-slate-600">{monthly.length ? "Your confirmed monthly editing capacity, with no automatic renewal or rollover." : "Choose a monthly plan for ongoing editing, or use a one-time video package."}</p><Link to="/dashboard/subscriptions" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold underline">View subscriptions →</Link></section>
      <section className="neo-workspace__panel rounded-3xl p-6" aria-labelledby="balance-title"><p className="neo-workspace__eyebrow">Credit balance</p><h3 id="balance-title" className="sr-only">Available editing balance</h3><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="text-3xl font-black tracking-tight">{hours.toLocaleString("en-US", { maximumFractionDigits: 2 })}</p><p className="mt-1 text-xs font-bold text-slate-600">Editing hours</p></div><div className="border-l border-slate-200 pl-5"><p className="text-3xl font-black tracking-tight">{videos}</p><p className="mt-1 text-xs font-bold text-slate-600">Video credits</p></div></div><p className="mt-5 text-xs leading-5 text-slate-600">Confirmed paid packages only. Hours are reserved when a project is submitted; each one-time project uses one video credit.</p></section>
    </div>
    {canStartProjects ? <section className="neo-workspace__panel rounded-2xl p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-5"><div className="max-w-xl"><p className="neo-workspace__eyebrow">Your next step</p><h3 className="mt-2 text-lg font-bold">{setupNeeded ? "Set up your creator profile." : hours > 0 || videos > 0 ? "Ready for your next video?" : "Find the right editing package."}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{setupNeeded ? "Complete a short creator profile to unlock projects. Your editor can work with any platform or website." : hours > 0 || videos > 0 ? "Your creator preferences are saved. Send the footage and brief to start an edit." : "Choose a package, complete your creator profile, and submit your first brief."}</p></div><Link to={setupNeeded ? "/dashboard/profile#channel-profile" : hours > 0 || videos > 0 ? "/dashboard/projects#new-project" : "/pricing"} className="neo-workspace__profile-submit inline-flex min-h-12 w-full shrink-0 items-center justify-center rounded-xl px-5 text-sm font-bold sm:w-auto">{setupNeeded ? "Complete creator profile →" : hours > 0 || videos > 0 ? "Start a project →" : "Explore packages →"}</Link></div></section> : null}
    {monthly.length ? <section aria-label="Monthly capacity periods" className="grid gap-4 sm:grid-cols-2">{monthly.map(p => <div key={p.id} className="neo-workspace__panel min-w-0 rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>{p.name}</strong><span>{p.remaining / 60} / {p.granted / 60} hours left</span></div><progress className="mt-4 h-2 w-full accent-slate-600" max={p.granted} value={p.used} aria-label={`${p.name}: ${p.used / 60} hours reserved of ${p.granted / 60}`} /><p className="mt-2 text-xs text-slate-600">{p.used / 60} hours reserved · Period ends {new Date(p.expiresAt!).toLocaleDateString("en-US", { timeZone: "UTC" })}</p></div>)}</section> : null}
  </div>;
}
